<?php
define('C_REST_WEB_HOOK_URL', 'https://dealexpertsrealestate.bitrix24.com/rest/76/wbocw4wnp63fyits/'); //url on creat Webhook

define('PROPERTY_LISTING_ENTITY_TYPE_ID', 1100);
define('INTERNAL_LISTING_ENTITY_TYPE_ID', 1100);
define('DEVELOPERS_ENTITY_TYPE_ID', 1104);
define('LISTING_AGENTS_ENTITY_TYPE_ID', 1108);
define('LOCATIONS_ENTITY_TYPE_ID', 1112);
define('LANDLORDS_ENTITY_TYPE_ID', 1116);
define('GENERAL_SETTINGS_ENTITY_TYPE_ID', 1122);
define('BAYUT_LOCATIONS_ENTITY_TYPE_ID', 1126);

define('CITIES_ENTITY_TYPE_ID', 1132);
define('COMMUNITIES_ENTITY_TYPE_ID', 1136);
define('SUB_COMMUNITIES_ENTITY_TYPE_ID', 1140);
define('BUILDINGS_ENTITY_TYPE_ID', 1144);

define('C_REST_BLOCK_LOG',true);//turn off default logs
